### ISSUE TITLE
Not a Issue

### ISSUE THREAD

**Issue by UnEnanoMas** [Muqsit/QueryManipulator#2]
Muqsit they have told me that you have a "hack" to extend the limit of blocks (which is 256) I am making a pixelart and I would like to know if you can give it to me or I have to buy it or something

**Comment by buchwasa** [comment]
https://github.com/Muqsit/WorldHeightHack

**Comment by UnEnanoMas** [comment]
I love you @buchwasa <3

**Comment by UnEnanoMas** [comment]
Bruh version (plugin requires one of: 4.0.0)

**Comment by UnEnanoMas** [comment]
I guess it's impossible gg
